config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews,
           -> { extending WithUserAssociationExtension },
           dependent: :destroy
  belongs_to :user
  validates :name, length: { minimum: 3 }, uniqueness: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def average_rating
    return 'N/A' if reviews.none?
    # byebug
    # reviews.inject(0) { |memo, review| memo + review.rating } / reviews.size
    reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  has_many :endorsements, dependent: :destroy
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  include RestaurantsHelper
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    unless current_user.restaurants.include? @restaurant
      flash[:notice] = 'error: you must be the author to edit a restaurant'
      redirect_to restaurants_path
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if current_user.restaurants.include? @restaurant
      @restaurant.destroy
      flash[:notice] = 'Restaurant deleted successfully'
    else
      flash[:notice] = "error: you are not the author of the entry for #{@restaurant.name}"
    end
    redirect_to restaurants_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include ReviewsHelper
  before_action :authenticate_user!

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)
    return redirect_to restaurants_path if @review.save
    if @review.errors[:user]
      flash[:notice] = 'error: you have already reviewed this restaurant'
      return redirect_to restaurants_path
    end
    return render :new
  end

  def destroy
    @review = Review.find(params[:id])
    if current_user.reviews.include? @review
      @review.destroy
      flash[:notice] = 'Review deleted successfully'
    else
      flash[:notice] = "error: you are not the author of the entry for this review"
    end
    redirect_to restaurants_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def restaurant_params
    params.require(:restaurant).permit(:name, :image)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating)
    "★" * rating.round + "☆" * remainder
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelp Clone</title>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
  <nav>
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Yelp Clone", restaurants_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to 'Add a restaurant', new_restaurant_path()%></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Log in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>
  <% if notice %>
  <div class="alert">
    <%= notice %>
  </div>
  <% end %>
  <section class="container content">
  <%= yield %>
  </section>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: {multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<!-- <% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
  <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
  <h3>Average rating: <%= star_rating(restaurant.average_rating) %></h3>
  <%= image_tag restaurant.image.url(:thumb) %>
  <h3>Reviews for <%= restaurant.name %></h3>
  <% if restaurant.reviews.any? %>
   <ul>
     <% restaurant.reviews.each do |review| %>
     <li>
       <%= review.thoughts %>
       <%= review.rating %> / 5
       <%= link_to "Delete review", review_path(review), method: :delete %>
       <%= link_to "Endorse review", review_endorsements_path(review), class: 'endorsements-link', method: :post %>
       <span class="endorsements_count"> <%= review.endorsements.count %> </span> <%= 'endorsement'.pluralize(review.endorsements.count) %>
     </li>
     <% end %>
  </ul>
  <% else %>
    No reviews yet <br><br>
  <% end %>
  <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
  <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
  <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
  <hr>
  <% end %>
<% else %>
  No restaurants yet
<% end %>
<%= link_to 'Add a restaurant', new_restaurant_path() %> -->



<% if @restaurants.any? %>
  <% @restaurants.each_with_index do |restaurant, i| %>
  <% if i % 3 == 0 %><div class="row"><% end %>
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <div class="panel panel-default <% if (i + 1) % 3 == 0 %>last<% end %>">
        <div class="panel-body">
          <section class="main-info" style='background-image: url("<%= restaurant.image.url(:medium) %>")'>
            <section class="basic-info">
              <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
            </section>
            <section class="rating">
              <%= star_rating(restaurant.average_rating) %>
            </section>
          </section>
          <section class="more-details">
            <section class="reviews-counter">
              <%= restaurant.reviews.count %> <%= 'review'.pluralize(restaurant.reviews.count) %>
            </section>
            <section class="actions pull-right">
              <%= link_to '', edit_restaurant_path(restaurant), title: "Edit #{restaurant.name}", class: 'glyphicon glyphicon-pencil' %>
              <%= link_to '', restaurant_path(restaurant), title: "Delete #{restaurant.name}", method: :delete, class: 'glyphicon glyphicon-trash' %>
              <%= link_to '', new_restaurant_review_path(restaurant), title: "Review #{restaurant.name}", class: 'glyphicon glyphicon-edit' %>
            </section>
          </section>
        </div>
      </div>
    </div>
  <% if (i + 1) % 3 == 0 || restaurant == @restaurants.last %></div><% end %>
  <% end %>
<% else %>
  No restaurants yet
<% end %>
<hr>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>
<%= render "form" %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.description %></p>
<h3>Reviews for <%= @restaurant.name %></h3>
<h3>Average rating: <%= star_rating(@restaurant.average_rating) %></h3>
<%= image_tag @restaurant.image.url(:thumb) %>
<% if @restaurant.reviews.any? %>
 <ul>
   <% @restaurant.reviews.each do |review| %>
   <li>
     <%= review.thoughts %>
     <%= review.rating %> / 5
     <%= link_to "Delete review", review_path(review), method: :delete %>
     <%= link_to "Endorse review", review_endorsements_path(review), class: 'endorsements-link', method: :post %>
     <span class="endorsements_count"> <%= review.endorsements.count %> </span> <%= 'endorsement'.pluralize(review.endorsements.count) %>
   </li>
   <% end %>
</ul>
<% else %>
  No reviews yet
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>